# Generated by Django 4.0.4 on 2022-09-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_is_student_user_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appointment_date',
        ),
    ]
