# Generated by Django 4.0.4 on 2022-07-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registered_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registered_user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='registered_user',
            name='username',
        ),
    ]
