# Generated by Django 4.0.4 on 2022-07-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_users', '0002_remove_registered_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
